# -*- coding: utf-8 -*-
"""Тренировка 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lkMwFV93ifgm5sbQiSb2_Zsd6YVqezug
"""

import math

a=5
b=2
print (a + b) #сложение
print (a - b) #вычитание
print (a * b) #умножение
print (a / b) #деление

a=5
b=2
print (a > b) #больше
print (a < b) #меньше
print (a == b) #равно
print (a != b) #не равно

print ("Hello! My name is Diana Davydova!") #вывод строки
x = input ("Введите число:") #ввод данных
print ("Вы ввели число" + x) #ввод строки с переменной