# -*- coding: utf-8 -*-
"""Тренировка 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OXE93OeqGdsB8cSlo0GriWl5embBsgxj
"""

pip install tensorflow

pip install tf-nightly

pip install keras

"""Импортируем модули:"""

import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import numpy as np
import matplotlib.pyplot as plt
from tensorflow import keras
from tensorflow.keras.layers import Dense

"""Два обучающих списка:"""

c = np.array([-40, -10, 0, 8, 15, 22, 38] ) #Цельсия
f = np.array([-40, 14, 32, 46, 59, 72, 100] ) #Фаренгейт

"""Последовательность модели"""

model = keras. Sequential()

model.add(Dense(units=1, input_shape=(1,), activation='linear'))

"""Комплектация с указанием критериев качества и способа оптимизации алгоритма градиентного спуска."""

model.compile(loss='mean_squared_error', optimizer=keras.optimizers.Adam(0.1))

"""Код для запуска:"""

history = model.fit(c, f, epochs=500, verbose=0)
print("Обучение завершено")

plt.plot(history.history['loss'])
plt.grid(True)
plt.slow()

"""Проверка работоспособности"""

print(model.predict([100]))

"""Отображение весовых коэффициентов:"""

print(model.get_weights())