# -*- coding: utf-8 -*-
"""Тренировка VGG19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XHzahX3uIGM2B2e2GrJ2CddPjJdYoUUo

Подключение библиотек
"""

import numpy as np
import matplotlib.pyplot as plt
from tensorflow import keras
from google.colab import files
from io import BytesIO
from PIL import Image

"""Инициализировать модель сети"""

model = keras.applications.VGG19()

"""Загрузка изображения"""

uploaded = files.upload()

img = Image.open(BytesIO(uploaded[list(uploaded.keys())[0]]))
plt.imshow( img )

"""Привести к входному формату"""

img = np.array(img)
x=keras.applications.vgg19.preprocess_input(img)
print(x.shape)
x = np.expand_dims(x,axis=0)

"""Загрузка в нейросеть"""

res = model.predict( x )
print(np.argmax(res))

"""В соответстви с базой изображений, 285 "Египетский кот"
"""