# -*- coding: utf-8 -*-
"""Тренировка 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q-v5bxd5HLv54Ga8aEQAR_Q5k31a5G3N

Подбор изображения

Подключение библиотек:
"""

import numpy as np
import matplotlib.pyplot as plt
from tensorflow import keras
from google.colab import files
from io import BytesIO
from PIL import Image

"""Инициализация модели сети"""

model = keras.applications.VGG16()

"""Загрузка изображения"""

uploaded = files.upload()

img = Image.open(BytesIO(uploaded[list(uploaded.keys())[0]]))
plt.imshow( img )

"""Привести изображение к входному формату VGG-сети"""

img = np.array(img)
x=keras.applications.vgg16.preprocess_input(img)
print(x.shape)
x = np.expand_dims(x,axis=0)

"""Загрузка обработанного изображения"""

res = model.predict( x )
print(np.argmax(res))

"""В соответстви с базой изображений, 285 "Египетский кот"
"""